### ISSUE TITLE
Progress angles with tibial torsion

### ISSUE THREAD

**Issue by aaa34169** [pyCGM2/pyCGM2#1] opened 2016-11-17 13:35 UTC
deviation on FootProgress angles ( see trace, figure at the bottom , on the right) between PyCGM2-model and Vicon Pig whan tibial torsion enable is questionable. 

![kinematics kadmed pycgm2 vs vicon](https://cloud.githubusercontent.com/assets/3098117/20391289/a98f9392-acca-11e6-93f2-ffc80ae52b2e.png)

euler angles shouldn t be affected by tibial torsion

Comment From richard:
_I’ve been thinking about this overnight and I just can’t see how it can be a problem with the calculations of the joint angles (e.g. the Cardan sequence used). This calculation is essentially of where the long axis of the foot is with regard to the global axis system and cannot possibly be (directly) affected by the tibial torsion of tibial offset.
The only two options I can see are if the position of the ankle joint centre is being incorrectly calculated or if the foot offset is being incorrectly incorporated into the model. (Note that these will obviously have an indirect effect on the joint angle calculation)._

**Comment by aaa34169** [comment] 2016-11-17 22:49
Richard-Morgan, 
Based on your comments, i went through my code in order to find an explanation about the FootProgress deviation between my CGM1-KADmed and the Vicon-CGM1.
 
Ankle Joint centres are correct. Thus, the deviation is brought about a difference between longitudinal axis of the foot.  The Z-axis ( longitudinal) of the CGM1 *corrected* foot is actually different from Vicon after *gait reconstruction*.

Let me explain
During **static calibration** , Vicon used the medio lateral axis of the distal shank for building both *corrected* and *uncorrected* foot Referentials. Foot offsets are extracted from the rotation matrix between these two referentials. Theoritically three offsets should be extracted. The cgm1  process only considers dorsiflexion offset and rotation offset. 
My code replicates this process perfectly. I got similar offsets 

During **dynamic reconstruction**, vicon  doesn t match its **static calibration** . Vicon 
is mistaken in taking the proximal shank axis for building the uncorrected foot Referential.  Therefore, application of foot offsets on this wrong *uncorrected* foot referential cant provide a similar longitudinal foot axis coming from the calculation with medio-lateral distal shank axis. There is a slight deviation.

Fabien

**Comment by rjbakersalford** [comment] 2016-11-18 07:25
Still not sure about this. Uncorrected foot referential (coordinate system) is (or should be) defined first by the line from ankle joint centre to toe marker and then by the axis from ankle joint centre to knee joint centre. This is clearly independent of tibial torsion. 

If you have used the medio-lateral axis of the tibia as the second axis used in defining the foot referential then you could well get the observed behaviour. 

Sorry its so late in the day but I've finally found a copy of my old bodybuilder code that shows this (extension changed from .mod to .txt so that I can upload it to GitHub).

[Caligula.txt](https://github.com/pyCGM2/pyCGM2/files/599255/Caligula.txt)

Richard

**Comment by aaa34169** [comment] 2016-11-18 07:53
Thank Richard 
I was pretty sure of your answer. 

 finally, the difference relies on the vector sequence used to compute the uncorrected foot. 
In a vicon document, it s written :
`A second foot segment is constructed, using the TOE-AJC as the primary axis, and
again the Y axis of the untorsioned tibia to define the perpendicular X axis and the foot Y
axis (the 'uncorrected' foot)` 

I have ever seen the sequence you mention. It was in the OFM bodybuilder code. 

I code it today.

regards
Fabien

**Comment by rjbakersalford** [comment] 2016-11-18 08:19
I think the bottom line is that the Vicon documentation is wrong not their code!

**Comment by aaa34169** [comment] 2016-11-18 12:23
The bodybuilder code is clear. However, it doesn t indicate how LStaticPlantFlex is calculated.
do you have a bodybuilder code for the static calibration. 

what you explain , match slides , i got from Gabriel Paolini. 
![paolini slide](https://cloud.githubusercontent.com/assets/3098117/20429947/8aabc0c6-ad89-11e6-9e61-a05f9780a80b.png)

Unfortunatly when i implement this sequence, my tests on static calibration fail.  I dont find the foot offset from nexus exactly. Maybe it,s an old release of the Plugin gait.  

The vicon matlab pig developped by vicon used the medio shank axis as second axis for foot referential  aparently.   
i am discussing with vicon developper to clarify this point.

**Comment by rjbakersalford** [comment] 2016-11-18 13:20
Fabien,

The whole reason I didn't make the BodyBuilder code more widely available is that I always meant to replicate the static calibration as well but never got around to it. The only testing I have ever done assumed that the offsets from the static calibration were correct and what we seem to be saying is that it is the static calibration that is wrong.

I should say that in everything else PiG has always been proved to be correct and internally consistent and I can't imagine that this sort of detail has changed with different versions.

I'm at home today but in on Mondya. I suggest that if things haven't been resolved by then that we have a chat about it together sometime on Monday.

Richard

**Comment by aaa34169** [comment] 2016-11-18 15:42
After emails and discussions, here is my conclusion... (for today) 

-  Both vicon Matlab-Pig ( Vicon product : Advanced Gait workflow) and my python CGM1 use the medio-lateral  shank axis for building the corrected foot and uncorrected foot referential. Both code replicate static offsets for each CGM1 variants. However, both code fail to replicate the ankle angle and foot progress angle with the CGM1 variant : KAD-Med.  This deviation is induced by the wrong shank axis ( proximal tibia instead of distal). I had a confirmation :

> Yes, changing that axis will alter the ankle and foot progress angles.

- the bodybuilder vector sequence for building foot referential fails to replicate native outputs with all CGM1 variants. For instance, with the simple CGM1, i got these dviation on foot offsets :

`LStaticPlantFlex : Vicon (4.698603)  Vs bodyBuilderFoot (4.700222)`
`RStaticPlantFlex : Vicon (4.431896)  Vs bodyBuilderFoot (4.461238)`
`LStaticRotOff : Vicon (-0.912755)  Vs bodyBuilderFoot (-0.904362)`
`RStaticRotOff : Vicon (3.499746)  Vs bodyBuilderFoot (3.462237)`

there is a clear impact on the FootProgress angle. ( Blue = nexus Output - Red =  bodybuilder Foot):
![2016-11-18 15_03_42-testusebodybuilderfoot c3d - mokka](https://cloud.githubusercontent.com/assets/3098117/20434649/a92dbe8e-ada0-11e6-9276-07c7728a3d4e.png)

**what is surprising, it's  i dont manage to  find a reference about this sequence.**  This sequence might be used in a version older than Nexus 1.5. 
it was told me from Vicon :

> There’s nothing in the source history to indicate we’ve ever used that definition. As far back as Nexus 1.5 it appears to use the shank y axis to define the foot.

when was developped Bodybuilder?  are there any documents validating its cgm1 process?

**Comment by rjbakersalford** [comment] 2016-11-18 17:31
A quick history lesson:

The Vicon Clinical Manager (VCM) was the first Vicon software to incorporate the CGM and came out in 1991. This was based on an amalgamation of the Davis and Kadaba codes. I don't think there was any modification of the underlying model throughout the lifetime of the the VCM indeed for a considerable period the source code was lost and when it was found it was found to be so badly written as to be virtually impossible to follow.

BodyBuilder was a separate modelling product that used BodyLanguage and was released in 1996. 
At a similar time (perhaps a little earlier) Vicon also introduced Workstation software to capture data.

PlugIn Gait was released in 1998 as a PlugIn to Workstation which processed the data in "exactly" the same way as VCM (Don't suppose this was ever checked with the rigour with which you are checking).

PiG was modified in 2002 to allow the medial malleolus for use on the static trial if the KAD was used and in 2005 to allow the medial malleolar marker to calibrate the shank offset from a statice trail even if the KAD was not used. The last development of PiG was in 2006 (as far as I am aware). 

Caligula (my Bodybuilder version of VCM) is dated as last being modified in 1999 but the DynaKAD software was based on Caligula and version 1.0 dates back to December 1998. I think I had done most of the work before PiG was released. Caligula was a result of genuine reverse engineering. There was no detailed documentation as there is today and this was at the time when Vicon couldn't find the original code. At this time I actually knew more about VCM than Vicon did! The only way I knew if Caligula was correct of not was whether it gave the same outputs as VCM. I judged success by whether the lines on Polygon graphs overlaid each other (i.e. I never checked at the level of precision that you are now working to).

At this level of precision I don't think whether you use the y-axis or the z-axis of the tibia as the secondary axis for the foot would make a detectable difference (but clearly it wouldn't give exactly the same result). This is rather a long way round to say that we should trust what Vicon tell us and accept that Caligula always was different (though I think we'd now agree that it is slightly more sensible in that it removes any dependency on tibial torsion and shank offset.

Just got your e-mail about Golem (I'd forgotten about him but the code is actually still available at http://www.clinicalgaitanalysis.com/bodybuilder/). You are correct this was a monster and it was Golem that drove me to write Caligula. Golem was Vicon's first attempt to write an equivalent of VCM in BodyLanguage at a time when they had lost the code. It worked reasonably well but not exactly because they couldn't work out how to apply the thigh and shank rotation offsets. These are defined (from the static trial) as being about the knee and ankle joint centres (defined by KAD and input tibial torsion respectively). The problem is that you don't know where the knee joint centre is in the walking trial so there is nothing to rotate about! They made a reasonable compromise of guessing at where the knee joint centre was on the basis of the thigh marker and then rotating about that. This meant that although the code agreed reasonably well with VCM it was sufficiently far away to give clinically important differences. It was me who worked out how to use  the thigh offset so specify the rotation  about the line from the hip joint to knee marker  that would put the knee in the correct place.

Interstingly if you look at that code it models the foot in the same way that I did. That is probably where I got it from. Even more interestingly in the comment section at the top it says:

_The results should however mimic VCM very closely, though the feet are 
modelled a bit differently and the static parameter values are different_

It could be that this difference is what we have uncovered from your work.

****Summarising** all of this we seem to have uncovered a longstanding bug in PiG (I suspect it has always been there). If my understanding is correct then the foot offsets (rotation in particular) are calculated from the static trial in a way that is incompatible with how they are used for the walking trial. 

To be more precise the static model calculates foot offsets with respect to the distal tibia and the dynamic trial applies them with respect to the proximal tibia. To put it another way the error in foot progression is approximately equal to the tibial torsion.**

That's amazing - PiG has been in operation for nearly 20 years in labs across the world and you are the first person to spot this! Congratulations.

I'm not sure what we do about this (other than demanding payment from Vicon to keep quiet about it.

Richard

PS the one group who have also written code which exactly mimics PiG are Gillette. I might ask Mike if he's come across this problem. I'll wait for your confirmation of the text in bold before I do so though.

**Comment by aaa34169** [comment] 2016-11-18 17:41
thank for this "quick " reply. I am reading again your reply to master it

**Comment by aaa34169** [comment] 2016-11-18 17:56
> ***Summarising* all of this we seem to have uncovered a longstanding bug in PiG (I suspect it has always been there). If my understanding is correct then the foot offsets (rotation in particular) are calculated from the static trial in a way that is incompatible with how they are used for the walking trial.
To be more precise the static model calculates foot offsets with respect to the distal tibia and the dynamic trial applies them with respect to the proximal tibia. To put it another way the error in foot progression is approximately equal to the tibial torsion.**

You are right. It s exactly what i did. 

just a quick comment about this :
>  to allow the medial malleolar marker to calibrate the shank offset from a statice trail even if the KAD was not used. 

i tried it out. that doesn t work. 
I got tibial torsion calculation with KAD and med only .

**Comment by rjbakersalford** [comment] 2016-11-18 17:57
Yes what started off as a quick reply didn't end up as one!

**Comment by aaa34169** [comment] 2016-11-18 18:00
i am going to submit a review based on your reply. 
great thank for your reply

**Comment by aaa34169** [comment] 2016-11-19 17:16
Richard, 
I ran a early openMA program this morning ( thank to my lovely boys) and was surprised openMA didn t get the same offset on the FootProgress Angle.  Since, arnaud and me follow the same process, that means there is a mistake somewhere. either in openMA or in my code.

I actually found an error in my program, the marker diameter was wrong when i computed the AJC from the mid maleolus. I saw that by decreasing the threshold of my static tests on Joint centre positions and static offsets 
Morgan acquisition were collected with 25 mm , and i keep 14 mm by default inside my code.
Now, the deviation with vicon on footProgress angle is weak as you can see in this picture.  
![2016-11-19 17_11_12-figure 4](https://cloud.githubusercontent.com/assets/3098117/20457072/40aa7042-ae7b-11e6-9d5c-b734295b94bd.png)

blue = Vicon 
red = OpenMA
greenCross =  my API

In other hand,  the deviation on the abd/add ankle angle is still there.

**Comment by Alzathar** [comment] 2016-11-19 22:13
The difference against Vicon is normal and due to the use of the _good_ medial axis of the shank (i.e. using the medial axis of the torsioned shank - distal reference frame). If @aaa34169 takes the same medial axis of the proximal shank frame (i.e. untorsioned shank), he will obtain the same result than Vicon.

In OpenMA, there is a hidden way to verify that in debug mode only. I tested it on two dataset (generated by Nexus 2.3 an 2.5). In both case, the RMS difference on the reference frame of each foot is below 1e-5.

**Closed** 2017-01-11 07:53 UTC
